import { Prisma } from "@prisma/client";
import prisma from "../../config/database.js";
import AppError from "../../common/errors/AppError.js";
import { writeAudit } from "../../common/utils/audit.js";
const DAY=86400000, dateKey=d=>new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())), addDays=(d,n)=>new Date(d.getTime()+n*DAY), daysBetween=(a,b)=>Math.floor((dateKey(b)-dateKey(a))/DAY), asArray=v=>Array.isArray(v)?v:[], pct=(v,t)=>Math.floor(Number(v||0)*t/100), dateString=d=>dateKey(d).toISOString().slice(0,10);
const blocked=(d,p)=>asArray(p.blockedDates).map(String).includes(dateString(d));
const preferred=(d,p)=>{const a=asArray(p.preferredLeaveDays);return !a.length||a.includes(d.getUTCDay())||a.includes(String(d.getUTCDay()));};
const working=(d,p)=>{const a=asArray(p.workingDays);return !a.length||a.includes(d.getUTCDay())||a.includes(String(d.getUTCDay()));};
async function getPolicyRecord(companyId,id,tx=prisma){const p=await tx.schedulingPolicy.findFirst({where:{id,companyId},include:{department:true}});if(!p)throw new AppError("Scheduling policy not found",404);return p;}
async function validateDepartment(companyId,id,tx=prisma){if(!id)return;const d=await tx.department.findFirst({where:{id,companyId,isActive:true}});if(!d)throw new AppError("Department not found in this company",400);}
async function validateShifts(companyId,ids,tx=prisma){if(!ids?.length)return;const n=await tx.shift.count({where:{companyId,id:{in:ids},isActive:true}});if(n!==ids.length)throw new AppError("One or more shifts do not belong to this company",400);}
export async function createPolicy(companyId,input){await validateDepartment(companyId,input.departmentId);await validateShifts(companyId,input.shiftIds);return prisma.schedulingPolicy.create({data:{companyId,...input}});}
export async function listPolicies(companyId,q){const page=q.page||1,limit=q.limit||20,where={companyId,...(q.departmentId?{departmentId:q.departmentId}:{})};const [data,total]=await Promise.all([prisma.schedulingPolicy.findMany({where,orderBy:[{departmentId:"asc"},{name:"asc"}],skip:(page-1)*limit,take:limit,include:{department:true}}),prisma.schedulingPolicy.count({where})]);return{data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
export const getPolicy=async(companyId,id)=>getPolicyRecord(companyId,id);
export async function updatePolicy(companyId,id,input){await getPolicyRecord(companyId,id);if(input.departmentId!==undefined)await validateDepartment(companyId,input.departmentId);await validateShifts(companyId,input.shiftIds);return prisma.schedulingPolicy.update({where:{id},data:input,include:{department:true}});}
export async function generate(companyId,userId,input,meta={}){const policy=await getPolicyRecord(companyId,input.policyId);if(!policy.isActive)throw new AppError("Scheduling policy is inactive",409);if(!policy.departmentId)throw new AppError("A generation policy must target a department",400);
return prisma.$transaction(async tx=>{const employees=await tx.employee.findMany({where:{companyId,departmentId:policy.departmentId,employmentStatus:"ACTIVE"},orderBy:[{employeeNumber:"asc"},{id:"asc"}]});if(!employees.length)throw new AppError("No active employees found in the selected department",409);
let shifts=[];if(policy.shiftEnabled){shifts=await tx.shift.findMany({where:{companyId,isActive:true,...(asArray(policy.shiftIds).length?{id:{in:asArray(policy.shiftIds).map(String)}}:{})},orderBy:{code:"asc"}});if(!shifts.length)throw new AppError("Shift scheduling is enabled but no active shifts are configured",409);}
const generation=await tx.scheduleGeneration.create({data:{companyId,policyId:policy.id,startDate:dateKey(input.startDate),endDate:dateKey(input.endDate),generatedById:userId,status:"DRAFT"}});
const total=employees.length,maxPct=policy.maxLeavePercent==null?total:Math.max(1,pct(policy.maxLeavePercent,total)),minByPct=policy.minStaffingPercent==null?total:Math.max(0,total-Math.ceil(pct(policy.minStaffingPercent,total))),minByCount=policy.minStaffingCount==null?total:Math.max(0,total-policy.minStaffingCount),maxLeave=Math.max(0,Math.min(maxPct,minByPct,minByCount));
const leaveEnabled=policy.leaveSchedulingMode!=="MANUAL"&&policy.leaveDurationDays>0&&maxLeave>0;const groupSize=Math.max(1,maxLeave),groups=Math.ceil(total/groupSize),leaveRanges=new Map();
if(leaveEnabled){let cursor=addDays(dateKey(input.startDate),policy.leaveCycleAfterDays??0);for(let g=0;g<groups;g++){let start=cursor,guard=0;while(start<=dateKey(input.endDate)&&guard++<370&&(blocked(start,policy)||!preferred(start,policy)))start=addDays(start,1);const end=addDays(start,policy.leaveDurationDays-1);const members=employees.filter((_,i)=>i%groups===g);if(start<=dateKey(input.endDate)){for(const e of members)leaveRanges.set(e.id,{start,end,g});cursor=addDays(end,1);}}}
const rows=[];for(let d=dateKey(input.startDate);d<=dateKey(input.endDate);d=addDays(d,1)){if(!working(d,policy))continue;const cycle=policy.rotationEnabled&&policy.rotationDays?Math.floor(daysBetween(dateKey(input.startDate),d)/policy.rotationDays):0;for(let i=0;i<employees.length;i++){const e=employees[i],r=leaveRanges.get(e.id),onLeave=r&&d>=r.start&&d<=r.end;const shiftId=!onLeave&&policy.shiftEnabled?shifts[(i+cycle)%shifts.length].id:null;rows.push({companyId,generationId:generation.id,employeeId:e.id,departmentId:e.departmentId,workDate:d,status:onLeave?"LEAVE":"WORK",shiftId,shiftCycle:cycle,leaveGroup:onLeave?r.g:null,reason:onLeave?"Automatic leave allocation":null});}}
if(!rows.length)throw new AppError("The selected period contains no working days under this policy",400);await tx.scheduleGenerationAssignment.createMany({data:rows});await writeAudit(tx,{companyId,actorUserId:userId,action:"CREATE",resource:"schedule_generation",resourceId:generation.id,requestId:meta.requestId,ipAddress:meta.ipAddress,userAgent:meta.userAgent,metadata:{policyId:policy.id,employees:employees.length,rows:rows.length}});return tx.scheduleGeneration.findUnique({where:{id:generation.id},include:{policy:true,assignments:{include:{employee:true,shift:true},orderBy:[{workDate:"asc"},{employeeId:"asc"}]}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function listGenerations(companyId,q){const page=q.page||1,limit=q.limit||20,where={companyId,...(q.status?{status:q.status}:{}),...(q.policyId?{policyId:q.policyId}:{})};const[data,total]=await Promise.all([prisma.scheduleGeneration.findMany({where,orderBy:{createdAt:"desc"},skip:(page-1)*limit,take:limit,include:{policy:{include:{department:true}},_count:{select:{assignments:true}}}}),prisma.scheduleGeneration.count({where})]);return{data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
export async function getGeneration(companyId,id){const r=await prisma.scheduleGeneration.findFirst({where:{companyId,id},include:{policy:{include:{department:true}},assignments:{include:{employee:true,shift:true},orderBy:[{workDate:"asc"},{employeeId:"asc"}]}}});if(!r)throw new AppError("Schedule generation not found",404);return r;}
export async function approve(companyId,userId,id,meta={}){const g=await getGeneration(companyId,id);if(g.status!=="DRAFT")throw new AppError("Only draft generations can be approved",409);return prisma.$transaction(async tx=>{const u=await tx.scheduleGeneration.update({where:{id},data:{status:"APPROVED",approvedById:userId}});await writeAudit(tx,{companyId,actorUserId:userId,action:"APPROVE",resource:"schedule_generation",resourceId:id,requestId:meta.requestId,metadata:{status:"APPROVED"}});return u;});}
export async function publish(companyId,userId,id,meta={}){const g=await getGeneration(companyId,id);if(!["DRAFT","APPROVED"].includes(g.status))throw new AppError("Only draft or approved generations can be published",409);return prisma.$transaction(async tx=>{const ids=[...new Set(g.assignments.map(x=>x.employeeId))];await tx.employeeShiftAssignment.updateMany({where:{companyId,employeeId:{in:ids},isActive:true,effectiveFrom:{lte:g.endDate},OR:[{effectiveTo:null},{effectiveTo:{gte:g.startDate}}]},data:{isActive:false,effectiveTo:new Date(g.startDate.getTime()-1000)}});const byEmployee=new Map();for(const r of g.assignments.filter(x=>x.status==="WORK"&&x.shiftId)){if(!byEmployee.has(r.employeeId))byEmployee.set(r.employeeId,[]);byEmployee.get(r.employeeId).push(r);}let created=0;for(const [employeeId,rows] of byEmployee){rows.sort((a,b)=>a.workDate-b.workDate);let current=null;for(const r of rows){if(!current||current.shiftId!==r.shiftId||daysBetween(current.to,r.workDate)!==1){if(current){await tx.employeeShiftAssignment.create({data:{companyId,employeeId,shiftId:current.shiftId,effectiveFrom:current.from,effectiveTo:current.to,isPrimary:true,isActive:true}});created++;}current={shiftId:r.shiftId,from:r.workDate,to:r.workDate};}else current.to=r.workDate;}if(current){await tx.employeeShiftAssignment.create({data:{companyId,employeeId,shiftId:current.shiftId,effectiveFrom:current.from,effectiveTo:current.to,isPrimary:true,isActive:true}});created++;}}const u=await tx.scheduleGeneration.update({where:{id},data:{status:"PUBLISHED",publishedAt:new Date()}});await writeAudit(tx,{companyId,actorUserId:userId,action:"UPDATE",resource:"schedule_generation",resourceId:id,requestId:meta.requestId,metadata:{status:"PUBLISHED",shiftAssignmentsCreated:created,plannedLeaveDays:g.assignments.filter(x=>x.status==="LEAVE").length}});return u;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
